# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEmiY2MS-C2CzqyAeuejUxgQtouUopvT
"""



# ============================================================
# CUSTOMER CHURN PREDICTION AND SEGMENTATION SYSTEM
# Complete Google Colab Implementation
# ============================================================

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

print("Libraries imported successfully!")


# ============================================================
# 2. CREATE OUTPUT FOLDER
# ============================================================

os.makedirs("outputs", exist_ok=True)

print("Output folder created successfully!")


# ============================================================
# 3. LOAD TELCO CUSTOMER CHURN DATASET
# ============================================================

url = "https://raw.githubusercontent.com/IBM/watsonx-ai-samples/master/cpd4.5/data/customer_churn/WA_FnUseC_TelcoCustomerChurn.csv"

df = pd.read_csv(url)

print("\nDataset loaded successfully!")
print("Dataset Shape:", df.shape)

print("\nFirst 5 rows:")
display(df.head())


# ============================================================
# 4. BASIC DATA INFORMATION
# ============================================================

print("\n" + "="*60)
print("DATASET INFORMATION")
print("="*60)

print("\nNumber of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
display(df.isnull().sum().to_frame("Missing Values"))


# ============================================================
# 5. DATA PREPROCESSING
# ============================================================

print("\n" + "="*60)
print("DATA PREPROCESSING")
print("="*60)

# Convert TotalCharges to numeric
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

print("\nTotalCharges converted to numeric.")


# Check missing values created by conversion
print("\nMissing TotalCharges values:")
print(df["TotalCharges"].isnull().sum())


# Remove irrelevant Customer ID
if "customerID" in df.columns:
    df = df.drop("customerID", axis=1)

print("\nCustomerID removed.")


# Convert Churn into numerical values
df["Churn"] = df["Churn"].map({
    "Yes": 1,
    "No": 0
})

print("\nChurn converted:")
print("0 = No Churn")
print("1 = Churn")


# ============================================================
# 6. EXPLORATORY DATA ANALYSIS
# ============================================================

print("\n" + "="*60)
print("EXPLORATORY DATA ANALYSIS")
print("="*60)


# ------------------------------------------------------------
# 6.1 Churn Distribution
# ------------------------------------------------------------

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="Churn"
)

plt.title("Customer Churn Distribution")
plt.xlabel("Churn (0 = No, 1 = Yes)")
plt.ylabel("Number of Customers")

plt.tight_layout()

plt.savefig(
    "outputs/01_churn_distribution.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 6.2 Contract Type vs Churn
# ------------------------------------------------------------

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="Contract",
    hue="Churn"
)

plt.title("Contract Type vs Customer Churn")
plt.xlabel("Contract Type")
plt.ylabel("Number of Customers")

plt.xticks(rotation=15)

plt.tight_layout()

plt.savefig(
    "outputs/02_contract_vs_churn.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 6.3 Monthly Charges Distribution
# ------------------------------------------------------------

plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x="MonthlyCharges",
    kde=True
)

plt.title("Distribution of Monthly Charges")
plt.xlabel("Monthly Charges")
plt.ylabel("Number of Customers")

plt.tight_layout()

plt.savefig(
    "outputs/03_monthly_charges.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 6.4 Tenure vs Churn
# ------------------------------------------------------------

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Churn",
    y="tenure"
)

plt.title("Tenure vs Customer Churn")
plt.xlabel("Churn (0 = No, 1 = Yes)")
plt.ylabel("Tenure (Months)")

plt.tight_layout()

plt.savefig(
    "outputs/04_tenure_vs_churn.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 6.5 Internet Service vs Churn
# ------------------------------------------------------------

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="InternetService",
    hue="Churn"
)

plt.title("Internet Service vs Customer Churn")
plt.xlabel("Internet Service")
plt.ylabel("Number of Customers")

plt.tight_layout()

plt.savefig(
    "outputs/05_internet_service_vs_churn.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 7. DEFINE FEATURES AND TARGET
# ============================================================

X = df.drop("Churn", axis=1)
y = df["Churn"]

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget variable: Churn")


# ============================================================
# 8. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\n" + "="*60)
print("TRAIN-TEST SPLIT")
print("="*60)

print("Training samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])


# ============================================================
# 9. IDENTIFY NUMERICAL AND CATEGORICAL FEATURES
# ============================================================

numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

print("\nNumerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)


# ============================================================
# 10. PREPROCESSING PIPELINE
# ============================================================

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)


categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)


preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_pipeline,
            numerical_features
        ),
        (
            "cat",
            categorical_pipeline,
            categorical_features
        )
    ]
)

print("\nPreprocessing pipeline created successfully!")


# ============================================================
# 11. DEFINE MACHINE LEARNING MODELS
# ============================================================

models = {

    "Logistic Regression":
        LogisticRegression(
            max_iter=1000
        ),

    "Decision Tree":
        DecisionTreeClassifier(
            max_depth=5,
            random_state=42
        ),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            class_weight="balanced"
        )
}


# ============================================================
# 12. TRAIN AND EVALUATE MODELS
# ============================================================

results = []
trained_models = {}
predictions = {}

print("\n" + "="*60)
print("MODEL TRAINING AND EVALUATION")
print("="*60)


for model_name, model in models.items():

    print("\n")
    print("-"*60)
    print("Training:", model_name)
    print("-"*60)

    pipeline = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "model",
                model
            )
        ]
    )

    # Train model
    pipeline.fit(
        X_train,
        y_train
    )

    # Predict
    y_pred = pipeline.predict(
        X_test
    )

    # Calculate metrics
    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    precision = precision_score(
        y_test,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        y_pred,
        zero_division=0
    )

    # Store results
    results.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    })

    trained_models[model_name] = pipeline
    predictions[model_name] = y_pred

    print("\nAccuracy :", round(accuracy, 4))
    print("Precision:", round(precision, 4))
    print("Recall   :", round(recall, 4))
    print("F1 Score :", round(f1, 4))

    print("\nClassification Report:")
    print(
        classification_report(
            y_test,
            y_pred,
            zero_division=0
        )
    )


# ============================================================
# 13. MODEL COMPARISON TABLE
# ============================================================

results_df = pd.DataFrame(results)

print("\n" + "="*60)
print("MODEL PERFORMANCE COMPARISON")
print("="*60)

display(
    results_df.round(4)
)


# Save results
results_df.to_csv(
    "outputs/model_results.csv",
    index=False
)


# ============================================================
# 14. MODEL COMPARISON GRAPH
# ============================================================

plt.figure(figsize=(10,6))

results_melted = results_df.melt(
    id_vars="Model",
    value_vars=[
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],
    var_name="Metric",
    value_name="Score"
)

sns.barplot(
    data=results_melted,
    x="Model",
    y="Score",
    hue="Metric"
)

plt.title("Machine Learning Model Performance Comparison")
plt.xlabel("Machine Learning Model")
plt.ylabel("Score")

plt.ylim(0, 1)

plt.xticks(rotation=15)

plt.tight_layout()

plt.savefig(
    "outputs/06_model_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 15. SELECT BEST MODEL
# ============================================================

best_model_name = results_df.loc[
    results_df["F1 Score"].idxmax(),
    "Model"
]

best_model = trained_models[
    best_model_name
]

best_predictions = predictions[
    best_model_name
]

best_f1 = results_df.loc[
    results_df["Model"] == best_model_name,
    "F1 Score"
].values[0]


print("\n" + "="*60)
print("BEST MODEL")
print("="*60)

print("Best Model :", best_model_name)
print("F1 Score   :", round(best_f1, 4))


# ============================================================
# 16. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    best_predictions
)

print("\nConfusion Matrix:")
print(cm)


plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "No Churn",
        "Churn"
    ],
    yticklabels=[
        "No Churn",
        "Churn"
    ]
)

plt.title(
    f"Confusion Matrix - {best_model_name}"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.tight_layout()

plt.savefig(
    "outputs/07_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 17. K-MEANS CUSTOMER SEGMENTATION
# ============================================================

print("\n" + "="*60)
print("K-MEANS CUSTOMER SEGMENTATION")
print("="*60)


# Select relevant customer behaviour features
cluster_features = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

cluster_data = df[
    cluster_features
].copy()


# Handle missing values
cluster_data = cluster_data.fillna(
    cluster_data.median()
)


print("\nFeatures used for clustering:")
print(cluster_features)


# ============================================================
# 18. STANDARDIZE CLUSTERING FEATURES
# ============================================================

cluster_scaler = StandardScaler()

cluster_scaled = cluster_scaler.fit_transform(
    cluster_data
)

print("\nClustering data standardized successfully!")


# ============================================================
# 19. FIND OPTIMAL NUMBER OF CLUSTERS
# ============================================================

silhouette_scores = []

K_values = range(2, 9)


print("\nSilhouette Scores:")

for k in K_values:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(
        cluster_scaled
    )

    score = silhouette_score(
        cluster_scaled,
        labels
    )

    silhouette_scores.append(
        score
    )

    print(
        "K =", k,
        "Silhouette Score =",
        round(score, 4)
    )


# ============================================================
# 20. SILHOUETTE SCORE GRAPH
# ============================================================

plt.figure(figsize=(8,5))

plt.plot(
    list(K_values),
    silhouette_scores,
    marker="o"
)

plt.title(
    "Silhouette Score for Different Number of Clusters"
)

plt.xlabel(
    "Number of Clusters (K)"
)

plt.ylabel(
    "Silhouette Score"
)

plt.grid(True)

plt.tight_layout()

plt.savefig(
    "outputs/08_silhouette_score.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 21. SELECT BEST K
# ============================================================

best_k = list(K_values)[
    np.argmax(silhouette_scores)
]

print("\nBest number of clusters:", best_k)


# ============================================================
# 22. FINAL K-MEANS MODEL
# ============================================================

final_kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

cluster_labels = final_kmeans.fit_predict(
    cluster_scaled
)

df["Cluster"] = cluster_labels

print("\nK-Means clustering completed successfully!")


# ============================================================
# 23. CLUSTER SIZE
# ============================================================

print("\nCustomers in each cluster:")

cluster_counts = (
    df["Cluster"]
    .value_counts()
    .sort_index()
)

display(
    cluster_counts.to_frame(
        "Number of Customers"
    )
)


# ============================================================
# 24. CLUSTER SUMMARY
# ============================================================

cluster_summary = df.groupby(
    "Cluster"
).agg({

    "tenure": "mean",

    "MonthlyCharges": "mean",

    "TotalCharges": "mean",

    "Churn": "mean"

}).round(2)


cluster_summary["Churn Rate (%)"] = (
    cluster_summary["Churn"] * 100
).round(2)


print("\n" + "="*60)
print("CUSTOMER CLUSTER SUMMARY")
print("="*60)

display(
    cluster_summary
)


cluster_summary.to_csv(
    "outputs/cluster_summary.csv"
)


# ============================================================
# 25. PCA DIMENSIONALITY REDUCTION
# ============================================================

pca = PCA(
    n_components=2
)

pca_result = pca.fit_transform(
    cluster_scaled
)


pca_df = pd.DataFrame(
    pca_result,
    columns=[
        "PC1",
        "PC2"
    ]
)

pca_df["Cluster"] = df[
    "Cluster"
].values


print("\nPCA completed successfully!")

print(
    "Variance explained by PC1:",
    round(
        pca.explained_variance_ratio_[0] * 100,
        2
    ),
    "%"
)

print(
    "Variance explained by PC2:",
    round(
        pca.explained_variance_ratio_[1] * 100,
        2
    ),
    "%"
)


# ============================================================
# 26. PCA CLUSTER VISUALIZATION
# ============================================================

plt.figure(figsize=(9,6))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="Cluster",
    palette="viridis",
    s=60
)

plt.title(
    "Customer Segmentation using K-Means and PCA"
)

plt.xlabel(
    "Principal Component 1"
)

plt.ylabel(
    "Principal Component 2"
)

plt.legend(
    title="Cluster"
)

plt.tight_layout()

plt.savefig(
    "outputs/09_pca_clusters.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 27. CHURN RATE BY CLUSTER
# ============================================================

cluster_churn = (
    df.groupby("Cluster")["Churn"]
    .mean()
    * 100
)


print("\nChurn rate for each cluster:")

display(
    cluster_churn.round(2).to_frame(
        "Churn Rate (%)"
    )
)


plt.figure(figsize=(8,5))

sns.barplot(
    x=cluster_churn.index,
    y=cluster_churn.values
)

plt.title(
    "Churn Rate by Customer Cluster"
)

plt.xlabel(
    "Customer Cluster"
)

plt.ylabel(
    "Churn Rate (%)"
)

plt.tight_layout()

plt.savefig(
    "outputs/10_cluster_churn_rate.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 28. IDENTIFY HIGH-RISK CLUSTER
# ============================================================

high_risk_cluster = cluster_churn.idxmax()

high_risk_rate = cluster_churn.max()


print("\n" + "="*60)
print("HIGH-RISK CUSTOMER SEGMENT")
print("="*60)

print(
    "High-risk Cluster:",
    high_risk_cluster
)

print(
    "Churn Rate:",
    round(
        high_risk_rate,
        2
    ),
    "%"
)


# ============================================================
# 29. HIGH-RISK CUSTOMER CHARACTERISTICS
# ============================================================

high_risk_customers = df[
    df["Cluster"] == high_risk_cluster
]


print("\nHigh-risk cluster characteristics:")

print(
    "Number of Customers:",
    len(high_risk_customers)
)

print(
    "Average Tenure:",
    round(
        high_risk_customers["tenure"].mean(),
        2
    ),
    "months"
)

print(
    "Average Monthly Charges:",
    round(
        high_risk_customers["MonthlyCharges"].mean(),
        2
    )
)

print(
    "Average Total Charges:",
    round(
        high_risk_customers["TotalCharges"].mean(),
        2
    )
)


# ============================================================
# 30. SAVE FINAL DATASET WITH CLUSTERS
# ============================================================

df.to_csv(
    "outputs/final_customer_churn_data.csv",
    index=False
)

print("\nFinal dataset saved successfully!")


# ============================================================
# 31. FINAL PROJECT SUMMARY
# ============================================================

print("\n")
print("="*70)
print("CUSTOMER CHURN PROJECT COMPLETED SUCCESSFULLY")
print("="*70)

print(
    "\nOriginal Dataset Size:",
    "7043 customers"
)

print(
    "Training Samples:",
    X_train.shape[0]
)

print(
    "Testing Samples:",
    X_test.shape[0]
)

print(
    "\nBest Classification Model:",
    best_model_name
)

print(
    "Best F1 Score:",
    round(
        best_f1,
        4
    )
)

print(
    "\nOptimal Number of Clusters:",
    best_k
)

print(
    "High-Risk Customer Cluster:",
    high_risk_cluster
)

print(
    "High-Risk Cluster Churn Rate:",
    round(
        high_risk_rate,
        2
    ),
    "%"
)


# ============================================================
# 32. LIST GENERATED FILES
# ============================================================

print("\n" + "="*60)
print("GENERATED OUTPUT FILES")
print("="*60)

for file in sorted(
    os.listdir("outputs")
):

    print("✓", file)

print("\nAll required analysis has been completed!")